In [4]:
import torch

`torch.flatten()`

In [5]:
# torch.flatten() : merge dimension of tensor
t=torch.ones(2,3,4,5)
print(t.shape) # torch.Size([2, 3, 4, 5])
print(torch.flatten(t).shape)  # torch.Size([120])
print(torch.flatten(t,start_dim=1).shape) # torch.Size([2, 60]), dim=-3
print(torch.flatten(t,start_dim=2).shape) # torch.Size([2, 3, 20]) dim=-2
print(torch.flatten(t,start_dim=3).shape) # torch.Size([2, 3, 4, 5]) dim=-1

torch.Size([2, 3, 4, 5])
torch.Size([120])
torch.Size([2, 60])
torch.Size([2, 3, 20])
torch.Size([2, 3, 4, 5])


`torch.squeeze()`

In [3]:
# torch.squeeze(Tensor,dim=0)
t=torch.ones(2,3,1,5,1)
print(t.shape) # torch.Size([2, 3, 1, 5, 1])
print(torch.squeeze(t).shape) # torch.Size([2, 3, 5])
print(torch.squeeze(t,dim=2).shape) # torch.Size([2, 3, 5,  1])

# torch.unsqueeze(Tensor,dim=0)
t=torch.ones(2,3,4)
print(torch.unsqueeze(t,dim=1).shape)
print(torch.unsqueeze(t,dim=0).shape)

torch.Size([2, 3, 1, 5, 1])
torch.Size([2, 3, 5])
torch.Size([2, 3, 5, 1])
torch.Size([2, 1, 3, 4])
torch.Size([1, 2, 3, 4])


`torch.reshape()`

In [42]:
# torch.permute() : change dimension
# https://sanghyu.tistory.com/3 : view, reshape, transpose, permute
# reshape : only valid for possible dimensions
t=torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12])
torch.reshape(t, [2,3,2])

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

#### `torch.view(-1,k)`

`view(-1,k)` means convert tensor into (? x k) : -1 means unknown

In [11]:
t=torch.tensor([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(t.shape)
print(t.view(6,2).shape)
print(t.view(-1,2).shape) #same result with view(-1,2)

torch.Size([2, 3, 2])
torch.Size([6, 2])
torch.Size([6, 2])


In [10]:
t=torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12])
t1=t.new(1,12)
t1=torch.linspace(0,1,12)
print(t1)

tensor([0.0000, 0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273,
        0.8182, 0.9091, 1.0000])


`torch.Tensor.new()` : generate new tensor with same datatype with `self`

It allocate memory randomly(?)

정수형 텐서에 `.new()`함수로 새로 복제를 하고, `linspace()`함수를 넣었을 때, 정수형으로 버림된 값만 나타났음 (`linspace(0,k,N)` : 0부터 k까지 N등분된 텐서를 리턴)

In [39]:
t=torch.tensor([12])
print(t)
t1=t.new(1,3,3)
t1[:, :, 0] = 1.
t1[:, :, 1] = torch.linspace(0, 1, 3)
t1[:, :, 2] = torch.linspace(0, 1, 3)
print(t1)

grid = torch.zeros(1,3,3,3)
grid[:, :, :, 0] = 1.
grid[:, :, :, 1] = torch.linspace(0, 1, 3)
grid[:, :, :, 2] = torch.linspace(0, 1, 3).unsqueeze(-1)   
print(grid)

tensor([12])
tensor([[[1, 0, 0],
         [1, 0, 0],
         [1, 1, 1]]])
